### ISSUE TITLE
Visualisation of Polygon-Values as Heatmap in ID-Editor

### ISSUE THREAD

**Issue by simnh** [energiekollektiv/openmod.sh#11]
I created a test scenario do

```
python misc/geojson2db.py data/scenarios/test3/test-id-visualisation.geojson
```

to load the scenario into your database schema. Then you can access the polygons (relations) 

`address:port/element/<element-id>/JSON` 

The value to display/plot is found under the tag 'value'  of hub_relation objects

**Comment by cswh** [comment]
now it should work with the new db structure. we still have to define what tag values should be used for the coloring.
