### ISSUE TITLE
Minor things for mcbeth improvement

### ISSUE THREAD

**Issue by cswh** [energiekollektiv/openmod.sh#22]
* [x] delete scenario button in scenario overview
* [x] dialogue when trying to import scenario with already existing name (abort, overwrite, change scenario name)
* [x] link from scenario overview to import
* [x] link from edit scenario to scenario overview
* [x] download scenario as json button
* [x] how to put slider values and max into db
* [x] logout link in main menu does not work properly @gnn

**Comment by simnh** [comment]
Download half finished...format is still not good...

**Comment by simnh** [comment]
Depending on the main menu we should maybe just move the scenario overview link right beside back to main menu...or philip decides...engough for today
