### ISSUE TITLE
TracebackException only for python >=3.5

### ISSUE THREAD

**Issue by cswh** [energiekollektiv/openmod.sh#3]
_From @cswh on November 10, 2016 7:14_

`from traceback import TracebackException as TE`

in scenario.py does not work in python 3.4. e.g. `pyhon setup-database.py` is not working due to that.

_Copied from original issue: energiekollektiv/openmod.sh-id#6_

**Comment by cswh** [comment]
@gnn @simnh this issue is obsolete?

**Comment by simnh** [comment]
I guess so, we do not use scenario.py anymore...and until now there is no error in the new 'simulation'-module (mcbeth)

**Comment by cswh** [comment]
mcbeth line 2
