### ISSUE TITLE
API elemets does not work properly

### ISSUE THREAD

**Issue by simnh** [energiekollektiv/openmod.sh#41]
Calling this for example: 

http://localhost:8000/API/elements?scenario_db_id=9&type=hub

with multiple scenario, the return value is not only hubs from one scenario but from many result...

@cswh: can you reproduce the error?

**Comment by cswh** [comment]
@simnh : you fixed that already in df5d81c253538dc633f5bffbeb7668482978d7a5?

**Comment by simnh** [comment]
yes
