### ISSUE TITLE
Checks for input values in scenario.py

### ISSUE THREAD

**Issue by simnh** [energiekollektiv/openmod.sh#5]
- how to handle not exist values (installed_power, etc) 
- transmissions line if both hubs exist
- if load_profile is not there
- etc...

**Comment by cswh** [comment]
everything should be in db and provided via json api so far. or not?

I would suggest: if something is missing: throw an error.

**Comment by simnh** [comment]
This is still from the old simulation module, and I agree with you...and it is implemented this way. Maybe it would be good to have a 'full-check' for a scenario that checks it coherence (somewhere central)...?

**Comment by simnh** [comment]
This will come up in testing, I will close this, we can have new issues once a problem arises...
