### ISSUE TITLE
Fast appearing modal dialogues may freeze page

### ISSUE THREAD

**Issue by gnn** [energiekollektiv/openmod.sh#53]
If I submit a job for which results already exist in the database, the "Job Submitted" dialogue may be replaced by the "Results exist in the DB" dialogue before I can press "Close" on the former. If that happens, the page freezes after I press "Close" on the latter. It looks like the browser is still expecting me to press cancel on the first dialogue but doesn't display it, so I'm stuck. In those cases I have to reload the page to do continue.
This is on 96e11c0eec00f5c705797298a7e475464a043ee6 and Firefox 51.0.1.

**Comment by gnn** [comment]
Hacky fix: since we're already querying the database for whether there are results fitting the simulation job, why not do this before submitting the job and just don't submit the job if we find s.th. That also gets rid of some superfluous computations.
I'll see whether I can do this easily.

**Comment by Donskelle** [comment]
https://github.com/energiekollektiv/openmod.sh/commit/68576a37dc9d0fd034ceb9ae8a91891fb8bdba5f
Die Runsimlation Funktion prüft nun selber, ob Ergebnisse verfügbar sind und sendet nur nen Put Request, wenn diese nicht da sind.

**Comment by cswh** [comment]
should be fixed now, at least with 22b3463d2102aae6d4e37498506282e1b25f2ada

@gnn can you check and close this issue if resolved?

**Comment by gnn** [comment]
Ok, I tested this and everything's fine. You can still create two overlapping modal dialogues by rapid clicking `Run Simulation` with results already existing in the database, but those no longer freeze the browser window. I'm closing this and #59.
