### ISSUE TITLE
Use multiple cores

### ISSUE THREAD

**Issue by gnn** [energiekollektiv/openmod.sh#55]
Right now simulation jobs are handled one at a time, so there's no real parallelisation going on in our app. If we want you change that, all we have to do is to change the rightmost `1` on [line 27 of `openmod/sh/gui.py`](https://github.com/energiekollektiv/openmod.sh/blob/156905abef22a7932bde87943892cc1d11002e9e/openmod/sh/gui.py#L27) to the maximum number of jobs which can be handled at the same time and change [line 5 of `openmod.sh.py`](https://github.com/energiekollektiv/openmod.sh/blob/156905abef22a7932bde87943892cc1d11002e9e/openmod.sh.py#L5) to start the openmod.sh web application with debugging disabled, i.e. with `debug=False`.
Not specifying a maximum number of jobs means that the maximum is automatically set to the number of cores.

**Comment by cswh** [comment]
works
