### ISSUE TITLE
Make Scenario Table Overview sortable 

### ISSUE THREAD

**Issue by simnh** [energiekollektiv/openmod.sh#60]
Sortable by: Scenario Name (Frist column), Scenario Year (second column). 

Default, when landing on page: Sorted by name

**Comment by Donskelle** [comment]
https://github.com/energiekollektiv/openmod.sh/commit/456d9317eab966f7c492045a94eeb8c6268ee434
ist eingefügt

**Comment by simnh** [comment]
Ah ok this is fixed sorting, which is ok for now, but later we might want to add buttons for users to sort ...I leave it open.

Thanks so far!

**Comment by cswh** [comment]
the button is beside the column name...
