### ISSUE TITLE
Add Info if/if not results exist in database in scenario overview

### ISSUE THREAD

**Issue by simnh** [energiekollektiv/openmod.sh#67]
Can you try to hide the download results buttom if no results exist in db? (either only hide, better would be to replace the button with something like: "No results"

The problem here is that you can not use result_exist from the edit scenario page, so you could have to
do a ajax request to the db for each scenario and check if results exist.

**Comment by Donskelle** [comment]
I would recommend expanding the api. I implemented a request to url: 'API/flow_results' but this returns hole dataset for scenarios.
Commit https://github.com/energiekollektiv/openmod.sh/commit/b022ef014ddf10a3dd6061dcf044b3b4497cf420

**Comment by simnh** [comment]
We can do that generally, but for now we could use this request and if data are returned-> show download button? Then we could replace the request with a different reduced api call...

**Comment by Donskelle** [comment]
I have no idea how long it will take.

**Comment by simnh** [comment]
mh ok, but the rewuest works? then I can check tomorrow

**Comment by Donskelle** [comment]
Ya

**Comment by simnh** [comment]
ok then I will have a look at it tomorrow. thx...

**Comment by simnh** [comment]
This works now, we still need to check how that works with many different users on the server...closing this for now
