### ISSUE TITLE
Automatic updates of plots does not work anymore

### ISSUE THREAD

**Issue by simnh** [energiekollektiv/openmod.sh#69]
If the scenario is edited and a input plot is selected, the plot does not update when sliders are changed...this worked before

@Donskelle : Can you check if you can figure out what is wrong there?

**Comment by simnh** [comment]
Seems only to be the case for Input Stacked plot.....

**Comment by Donskelle** [comment]
Should be fixed with: https://github.com/energiekollektiv/openmod.sh/commit/ffc397620168768a3a156034332f1004277775a7

**Comment by simnh** [comment]
Ah pretty cool that you did it, i was wondering if I again filed a non existing bug as it worked again...THX
