### ISSUE TITLE
Add local emission factor (heat/electricity) Kiel

### ISSUE THREAD

**Issue by tnomas** [energiekollektiv/openmod.sh#71]
Add an emission factor in the "result summary" for heat and electricity produced in Kiel.

- (emissions **electricity** kiel)/(total **electricity** production kiel) = emission factor
- (emissions **heat** kiel)/(total **heat** production kiel) = emission factor

unit: gramm/kWh or tonns/MWh

**Comment by simnh** [comment]
did it...right now its still t/GWh because of rounding, but i will change that to t/MWh
