### ISSUE TITLE
Jobs fail to get listed (process error...?)

### ISSUE THREAD

**Issue by simnh** [energiekollektiv/openmod.sh#76]
From error log: 

```
[Sun Apr 09 20:50:48.704336 2017] [wsgi:error] [pid 14194:tid 140701232359168] [remote 2.240.60.13:51085] mod_wsgi (pid=14194): Exception occurred processing WSGI script '/home/kiel1/openmod.sh/openmod.sh.wsgi'.
[Sun Apr 09 20:50:48.704515 2017] [wsgi:error] [pid 14194:tid 140701232359168] [remote 2.240.60.13:51085] OSError: failed to write data
[Sun Apr 09 20:54:29.701214 2017] [wsgi:error] [pid 14196:tid 140701157213952] (70008)Partial results are valid but processing is incomplete: [client 93.207.60.117:35376] mod_wsgi (pid=14196): Unable to get bucket brigade for request., referer: http://kiel.openmod.net/edit_scenario?id=222
[Sun Apr 09 20:54:29.702738 2017] [wsgi:error] [pid 14194:tid 140701232359168] [remote 93.207.60.117:63629] mod_wsgi (pid=14194): Exception occurred processing WSGI script '/home/kiel1/openmod.sh/openmod.sh.wsgi'.
[Sun Apr 09 20:54:29.702850 2017] [wsgi:error] [pid 14194:tid 140701232359168] [remote 93.207.60.117:63629] OSError: failed to write data
```

**Comment by simnh** [comment]
I think this is not feasibility, as the problems are all feasible. I set up another instance without wsgi only pure python on port 5000...There sometimes if you click 'run simulation' the server response is 400..sometimes it works....don't know why...

**Comment by gnn** [comment]
Ok, so I changed (fixed) when and how notifications of started jobs are displayed. If one is careful and waits until jobs are done uploading, there seems to be no error. At least I couldn't reproduce one.
I started up to seven jobs, around twelve in total, for five different scenarios, cancelled and killed some of them and had three job uploads in parallel without getting a single error. All of them registered within a reasonable time frame.
Please stress test to check whether I'm just lucky.
