### ISSUE TITLE
Router erweitern + login required einfügen

### ISSUE THREAD

**Issue by Donskelle** [energiekollektiv/openmod.sh#9]
Redirect zur Loginseite für /static/iD/timeseries/* und /static/iD/* einfügen. 
Ich prüfe JS-Seitig aktuell nur, ob ein Json String zurück kommt, diese Prüfung kann ja drin bleiben

**Comment by cswh** [comment]
gilt auch für mehr routes als oben angegeben. also alle einmal durchschauen.
